version: "3.8"

services:
  decision:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=decision
    ports:
      - 5432:5432
